@allowed([
  'ppd'
  'prd'
])
param environment string = 'ppd'
param NetworkWatcherName string
param ConnectionMonitorName string
param endpoints array
param testConfigurations array
param testGroups array
param Dashboard_name string
param DashboardTitle string
param WorkspaceId string
param actiongroupsId string
param metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir01_Datalake_Primary_Blob_Service_name string
param metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir01_Datalake_Primary_File_Service_name string
param metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir01_Datalake_Secondary_Blob_Service_name string
param metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir01_Datalake_Secondary_File_Service_name string
param metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir02_Datalake_Primary_Blob_Service_name string
param metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir02_Datalake_Primary_File_Service_name string
param metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir02_Datalake_Secondary_Blob_Service_name string
param metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir02_Datalake_Secondary_File_Service_name string
param metricalerts_DSS_Network_Availability_from_OP_Datalake_Primary_Blob_Service_name string
param metricAlerts_DSS_Network_Availability_from_OP_Datalake_Primary_File_Service_name string
param metricAlerts_DSS_Network_Availability_from_OP_Datalake_Secondary_Blob_Service_name string
param metricAlerts_DSS_Network_Availability_from_OP_Datalake_Secondary_File_Service_name string
param metricalerts_DSS_Network_Availability_From_CTH_Datalake_Primary_Blob_Service_name string
param metricAlerts_DSS_Network_Availability_from_CTH_Datalake_Primary_File_Service_name string
param metricAlerts_DSS_Network_Availability_from_CTH_Datalake_Secondary_Blob_Service_name string
param metricAlerts_DSS_Network_Availability_from_CTH_Datalake_Secondary_File_Service_name string
param metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg01_Datalake_Primary_Blob_Service_name string
param metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg01_Datalake_Primary_File_Service_name string
param metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg01_Datalake_Secondary_Blob_Service_name string
param metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg01_Datalake_Secondary_File_Service_name string
param metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg02_Datalake_Primary_Blob_Service_name string
param metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg02_Datalake_Primary_File_Service_name string
param metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg02_Datalake_Secondary_Blob_Service_name string
param metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg02_Datalake_Secondary_File_Service_name string

var environmentsettings = {
  ppd: {
    TargetResouceGoup: 'tnc-monitoring-dbs-ppd-we'
  }
  prd: {
    TargetResouceGoup: 'tnc-monitoring-dbs-prd-we'
  }
}

resource NetworkWatcher_westeurope_ConnectionMonitorName 'Microsoft.Network/networkWatchers/connectionMonitors@2019-07-01' = {
  name: 'NetworkWatcher_westeurope/${ConnectionMonitorName}'
  location: resourceGroup().location
  properties: {
    endpoints: endpoints
    testConfigurations: testConfigurations
    testGroups: testGroups
    outputs: [
      {
        type: 'Workspace'
        workspaceSettings: {
          workspaceResourceId: WorkspaceId
        }
      }
    ]
  }
}

module DashboardAndAlerts './nested_DashboardAndAlerts.bicep' = {
  name: 'DashboardAndAlerts'
  scope: resourceGroup(environmentsettings[environment].TargetResouceGoup)
  params: {
    actiongroupsId: actiongroupsId
    NetworkWatcherName: NetworkWatcherName
    ConnectionMonitorName: ConnectionMonitorName
    Dashboard_name: Dashboard_name
    DashboardTitle: DashboardTitle
    endpoints: endpoints
    metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir01_Datalake_Primary_Blob_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir01_Datalake_Primary_Blob_Service_name
    metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir01_Datalake_Primary_File_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir01_Datalake_Primary_File_Service_name
    metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir01_Datalake_Secondary_Blob_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir01_Datalake_Secondary_Blob_Service_name
    metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir01_Datalake_Secondary_File_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir01_Datalake_Secondary_File_Service_name
    metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir02_Datalake_Primary_Blob_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir02_Datalake_Primary_Blob_Service_name
    metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir02_Datalake_Primary_File_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir02_Datalake_Primary_File_Service_name
    metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir02_Datalake_Secondary_Blob_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir02_Datalake_Secondary_Blob_Service_name
    metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir02_Datalake_Secondary_File_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_IR_tncdatavmir02_Datalake_Secondary_File_Service_name
    metricalerts_DSS_Network_Availability_from_OP_Datalake_Primary_Blob_Service_name: metricalerts_DSS_Network_Availability_from_OP_Datalake_Primary_Blob_Service_name
    metricAlerts_DSS_Network_Availability_from_OP_Datalake_Primary_File_Service_name: metricAlerts_DSS_Network_Availability_from_OP_Datalake_Primary_File_Service_name
    metricAlerts_DSS_Network_Availability_from_OP_Datalake_Secondary_Blob_Service_name: metricAlerts_DSS_Network_Availability_from_OP_Datalake_Secondary_Blob_Service_name
    metricAlerts_DSS_Network_Availability_from_OP_Datalake_Secondary_File_Service_name: metricAlerts_DSS_Network_Availability_from_OP_Datalake_Secondary_File_Service_name
    metricalerts_DSS_Network_Availability_From_CTH_Datalake_Primary_Blob_Service_name: metricalerts_DSS_Network_Availability_From_CTH_Datalake_Primary_Blob_Service_name
    metricAlerts_DSS_Network_Availability_from_CTH_Datalake_Primary_File_Service_name: metricAlerts_DSS_Network_Availability_from_CTH_Datalake_Primary_File_Service_name
    metricAlerts_DSS_Network_Availability_from_CTH_Datalake_Secondary_Blob_Service_name: metricAlerts_DSS_Network_Availability_from_CTH_Datalake_Secondary_Blob_Service_name
    metricAlerts_DSS_Network_Availability_from_CTH_Datalake_Secondary_File_Service_name: metricAlerts_DSS_Network_Availability_from_CTH_Datalake_Secondary_File_Service_name
    metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg01_Datalake_Primary_Blob_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg01_Datalake_Primary_Blob_Service_name
    metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg01_Datalake_Primary_File_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg01_Datalake_Primary_File_Service_name
    metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg01_Datalake_Secondary_Blob_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg01_Datalake_Secondary_Blob_Service_name
    metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg01_Datalake_Secondary_File_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg01_Datalake_Secondary_File_Service_name
    metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg02_Datalake_Primary_Blob_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg02_Datalake_Primary_Blob_Service_name
    metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg02_Datalake_Primary_File_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg02_Datalake_Primary_File_Service_name
    metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg02_Datalake_Secondary_Blob_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg02_Datalake_Secondary_Blob_Service_name
    metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg02_Datalake_Secondary_File_Service_name: metricAlerts_DSS_Network_Availability_from_AZ_OPGD_tncdatavmopdg02_Datalake_Secondary_File_Service_name
  }
}